services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: yarn install && cd apps/backend && yarn build
    startCommand: cd apps/backend && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      - key: GITHUB_CLIENT_ID
        value: ${GITHUB_CLIENT_ID}
      - key: GITHUB_CLIENT_SECRET
        value: ${GITHUB_CLIENT_SECRET}
      - key: ALLOWED_HOSTS
        value: ${ALLOWED_HOSTS}
      - key: AUTH_REDIRECT_URL
        value: ${ALLOWED_HOSTS}/auth/callback
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true

  - type: web
    name: ws
    env: node
    plan: free
    buildCommand: yarn install && cd apps/ws && yarn build
    startCommand: cd apps/ws && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      - key: ALLOWED_HOSTS
        value: ${ALLOWED_HOSTS}
      - key: AUTH_REDIRECT_URL
        value: ${ALLOWED_HOSTS}/game/random
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true

  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: yarn install && cd apps/frontend && yarn build
    startCommand: cd apps/frontend && npx serve dist -l $PORT -s
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_BACKEND_URL
        value: ${VITE_APP_BACKEND_URL}
      - key: VITE_APP_WS_URL
        value: ${VITE_APP_WS_URL}
